services:

  test:
    image: golang:1.24
    volumes:
      - ".:/src"
    environment:
      TEST_DB: "postgres://test:test@database/test?sslmode=disable"
    working_dir: "/src"
    command: "go test ./..."
